version: "3"

networks:
  local_network:
    external: true
  internal:
    external: false

services:
  api:
    ports:
      - "1337:1337"
    networks:
      - local_network
      - internal
  db:
    networks:
      - internal