version: "3"

networks:
  proxy:
    external: true
  internal:
    external: false

services:
  cms:
    labels:
      - traefik.backend=juandastic_api
      - traefik.frontend.rule=Host:api.juandastic.co
      - traefik.docker.network=proxy
      - traefik.port=1337
    networks:
      - internal
      - proxy
  db:
    networks:
      - internal
    labels:
      - traefik.enable=false