version: "3"

networks:
  proxy:
    external: true
  internal:
    external: false

services:
  server:
    labels:
      - traefik.backend=juandastic_api
      - traefik.frontend.rule=Host:api.juandastic.co
      - traefik.docker.network=proxy
      - traefik.port=80
    environment:
      PORT: 80
      NODE_ENV: production
    networks:
      proxy:
        aliases:
          - api.juandastic.co
      internal:
  db:
    networks:
      - internal
    labels:
      - traefik.enable=false