version: "3"
services:
  server:
    build: ./
    volumes:
      - ./:/app
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password_db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password_db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
